/*
 * IPSO Registry
 *
 * OMA IPSO registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Type the model 'Type'
type Type string

// List of Type
const (
	STRING Type = "String"
	BOOLEAN Type = "Boolean"
	INTEGER Type = "Integer"
	FLOAT Type = "Float"
	OBJ_LINK Type = "ObjLink"
	OPAQUE Type = "Opaque"
)
