/*
 * IPSO Registry
 *
 * OMA IPSO registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OperationType the model 'OperationType'
type OperationType string

// List of OperationType
const (
	R OperationType = "R"
	W OperationType = "W"
	RW OperationType = "RW"
	E OperationType = "E"
)
