/*
 * LwM2M Registry
 *
 * OMA LwM2M registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Error struct for Error
type Error struct {
	Code int32 `json:"code" xml:"code"`
	Message string `json:"message" xml:"message"`
}
