/*
 * IPSO Registry
 *
 * OMA IPSO registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ObjectResources struct for ObjectResources
type ObjectResources struct {
	Item []Resource `json:"Item,omitempty" xml:"Item"`
}
