/*
 * LwM2M Registry
 *
 * OMA LwM2M registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Lwm2M struct for Lwm2M
type Lwm2M struct {
	Object Object `json:"Object,omitempty" xml:"Object"`
}
