/*
 * IPSO Registry
 *
 * OMA IPSO registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MandatoryType the model 'MandatoryType'
type MandatoryType string

// List of MandatoryType
const (
	MANDATORY MandatoryType = "Mandatory"
	OPTIONAL MandatoryType = "Optional"
)
