/*
 * IPSO Registry
 *
 * OMA IPSO registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Resource struct for Resource
type Resource struct {
	ID int32 `json:"ID" xml:"ID,attr"`
	Name string `json:"Name" xml:"Name"`
	Operations OperationType `json:"Operations" xml:"Operations"`
	MultipleInstances InstanceType `json:"MultipleInstances" xml:"MultipleInstances"`
	Mandatory MandatoryType `json:"Mandatory" xml:"Mandatory"`
	Type Type `json:"Type" xml:"Type"`
	RangeEnumeration string `json:"RangeEnumeration,omitempty" xml:"RangeEnumeration"`
	Units string `json:"Units,omitempty" xml:"Units"`
	Description string `json:"Description,omitempty" xml:"Description"`
}
