/*
 * LwM2M Registry
 *
 * OMA LwM2M registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Item struct for Item
type Item struct {
	Name              string        `json:"Name,omitempty"`
	Operations        OperationType `json:"Operations,omitempty"`
	MultipleInstances InstanceType  `json:"MultipleInstances,omitempty"`
	Mandatory         MandatoryType `json:"Mandatory,omitempty"`
	Type              Type          `json:"Type,omitempty"`
	RangeEnumeration  string        `json:"RangeEnumeration,omitempty"`
	Units             string        `json:"Units,omitempty"`
	Description       string        `json:"Description,omitempty"`
}
