/*
 * LwM2M Registry
 *
 * OMA LwM2M registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Resource struct for Resource
type Resource struct {
	ID int32 `json:"ID,omitempty" xml:"ID,attr"`
	Name string `json:"Name,omitempty" xml:"Name"`
	Operations OperationType `json:"Operations,omitempty" xml:"Operations"`
	MultipleInstances InstanceType `json:"MultipleInstances,omitempty" xml:"MultipleInstances"`
	Mandatory MandatoryType `json:"Mandatory,omitempty" xml:"Mandatory"`
	Type Type `json:"Type,omitempty" xml:"Type"`
	RangeEnumeration string `json:"RangeEnumeration,omitempty" xml:"RangeEnumeration"`
	Units string `json:"Units,omitempty" xml:"Units"`
	Description string `json:"Description,omitempty" xml:"Description"`
}
