/*
 * LwM2M Registry
 *
 * OMA LwM2M registry service providing interface for objects and resources searching
 *
 * API version: 1.0.0
 * Contact: aliaksei.zhuk@dualinventive.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InstanceType the model 'InstanceType'
type InstanceType string

// List of InstanceType
const (
	MULTIPLE InstanceType = "Multiple"
	SINGLE   InstanceType = "Single"
)
