// Code generated by go-swagger; DO NOT EDIT.

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aliakseiz/lwm2m-registry-importer/rest/models"
)

// GetObjectReader is a Reader for the GetObject structure.
type GetObjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetObjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetObjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetObjectOK creates a GetObjectOK with default headers values
func NewGetObjectOK() *GetObjectOK {
	return &GetObjectOK{}
}

/*GetObjectOK handles this case with default header values.

Successful operation
*/
type GetObjectOK struct {
	Payload *models.LWM2M
}

func (o *GetObjectOK) Error() string {
	return fmt.Sprintf("[GET /ObjectDetails][%d] getObjectOK  %+v", 200, o.Payload)
}

func (o *GetObjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LWM2M)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
