// Code generated by go-swagger; DO NOT EDIT.

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/aliakseiz/lwm2m-registry-importer/rest/models"
)

// GetObjectsReader is a Reader for the GetObjects structure.
type GetObjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetObjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetObjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetObjectsOK creates a GetObjectsOK with default headers values
func NewGetObjectsOK() *GetObjectsOK {
	return &GetObjectsOK{}
}

/*GetObjectsOK handles this case with default header values.

Successful operation
*/
type GetObjectsOK struct {
	Payload models.Objects
}

func (o *GetObjectsOK) Error() string {
	return fmt.Sprintf("[GET /Object][%d] getObjectsOK  %+v", 200, o.Payload)
}

func (o *GetObjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
