// Code generated by go-swagger; DO NOT EDIT.

package object

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new object API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for object API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetObject gets details of a single object

Retrieve an XML containing the detailed description of a single object
*/
func (a *Client) GetObject(params *GetObjectParams) (*GetObjectOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetObjectParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getObject",
		Method:             "GET",
		PathPattern:        "/ObjectDetails",
		ProducesMediaTypes: []string{"text/xml"},
		ConsumesMediaTypes: []string{"text/xml"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetObjectReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetObjectOK), nil

}

/*
GetObjects gets metadata of all objects

Retrieve a JSON containing all the metadata information on all the Object Versions
*/
func (a *Client) GetObjects(params *GetObjectsParams) (*GetObjectsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetObjectsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getObjects",
		Method:             "GET",
		PathPattern:        "/Object",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetObjectsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetObjectsOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
