// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// MandatoryType mandatory type
// swagger:model MandatoryType
type MandatoryType string

const (

	// MandatoryTypeMandatory captures enum value "Mandatory"
	MandatoryTypeMandatory MandatoryType = "Mandatory"

	// MandatoryTypeOptional captures enum value "Optional"
	MandatoryTypeOptional MandatoryType = "Optional"
)

// for schema
var mandatoryTypeEnum []interface{}

func init() {
	var res []MandatoryType
	if err := json.Unmarshal([]byte(`["Mandatory","Optional"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		mandatoryTypeEnum = append(mandatoryTypeEnum, v)
	}
}

func (m MandatoryType) validateMandatoryTypeEnum(path, location string, value MandatoryType) error {
	if err := validate.Enum(path, location, value, mandatoryTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this mandatory type
func (m MandatoryType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateMandatoryTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
