// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ObjectMeta object meta
// swagger:model ObjectMeta
type ObjectMeta struct {

	// description
	Description string `json:"Description,omitempty"`

	// label
	Label string `json:"Label,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// object ID
	ObjectID int64 `json:"ObjectID,omitempty"`

	// object link
	ObjectLink string `json:"ObjectLink,omitempty"`

	// object link visible
	ObjectLinkVisible string `json:"ObjectLinkVisible,omitempty"`

	// owner
	Owner string `json:"Owner,omitempty"`

	// spec link
	SpecLink string `json:"SpecLink,omitempty"`

	// spec link visible
	SpecLinkVisible string `json:"SpecLinkVisible,omitempty"`

	// u r n
	URN string `json:"URN,omitempty"`

	// ver
	Ver string `json:"Ver,omitempty"`

	// vorto link
	VortoLink string `json:"VortoLink,omitempty"`
}

// Validate validates this object meta
func (m *ObjectMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ObjectMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ObjectMeta) UnmarshalBinary(b []byte) error {
	var res ObjectMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
